name: PHPUnit tests

on:
  workflow_call:
    inputs:
      PHP_MATRIX:
        description: 'Defines a matrix of PHP versions as JSON-string like following: "[\"7.4\", \"8.0\"]".'
        default: '["7.4"]'
        required: false
        type: string
      PHPUNIT_ARGS:
        description: 'Extra arguments to pass to the PHPUnit binary.'
        default: ''
        required: false
        type: string
    secrets:
      COMPOSER_AUTH_JSON:
        description: 'Defines the JSON as string for auth.json to use for private packagist services.'
        required: false

jobs:
  phpunit:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ${{fromJson(inputs.PHP_MATRIX)}}
    env:
      COMPOSER_AUTH: '${{ secrets.COMPOSER_AUTH_JSON }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install composer dependencies (use cache)
        uses: ramsey/composer-install@v1
        with:
          composer-options: "--prefer-dist"

      - name: Run PHPUnit
        run: "vendor/phpunit/phpunit/phpunit ${{inputs.PHPUNIT_ARGS}} --coverage-text"
