name: PHP static code analysis

on:
  workflow_call:
    secrets:
      COMPOSER_AUTH_JSON:
        description: 'Authentication for privately hosted packages and repositories as a JSON formatted object.'
        required: false

jobs:
  static-analysis:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    env:
      COMPOSER_AUTH: '${{ secrets.COMPOSER_AUTH_JSON }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer,cs2pr

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v1
        with:
          composer-options: "--prefer-dist"

      - name: Run PHP_CodeSniffer
        run: vendor/squizlabs/php_codesniffer/bin/phpcs

      - name: Run Psalm
        run: vendor/vimeo/psalm/psalm --output-format=compact --no-cache

      - name: Annotate static code analysis violations
        if: always()
        run: cs2pr --graceful-warnings ./phpcs-report.xml
