name: PHPUnit tests

on:
  workflow_call:
    inputs:
      PHP_MATRIX:
        description: 'Matrix of PHP versions as a JSON formatted object.'
        default: '["7.4"]'
        required: false
        type: string
      PHPUNIT_ARGS:
        description: 'Additional arguments passed to the PHPUnit binary.'
        default: ''
        required: false
        type: string
    secrets:
      COMPOSER_AUTH_JSON:
        description: 'Authentication for privately hosted packages and repositories as a JSON formatted object.'
        required: false

jobs:
  phpunit:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ${{ fromJson(inputs.PHP_MATRIX) }}
    env:
      COMPOSER_AUTH: '${{ secrets.COMPOSER_AUTH_JSON }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: "--prefer-dist"

      - name: Run PHPUnit
        run: "vendor/phpunit/phpunit/phpunit ${{ inputs.PHPUNIT_ARGS }} --coverage-text"
