name: PHP static code analysis

on:
  workflow_call:
    secrets:
      COMPOSER_AUTH_JSON:
        description: 'Defines the JSON as string for auth.json to use for private packagist services.'
        required: false

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    env:
      COMPOSER_AUTH: '${{ secrets.COMPOSER_AUTH_JSON }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer,cs2pr

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install composer dependencies (use cache)
        uses: ramsey/composer-install@v1
        with:
          composer-options: "--prefer-dist"

      - name: Check coding standards PHP
        run: vendor/squizlabs/php_codesniffer/bin/phpcs

      - name: Check Psalm
        run: vendor/vimeo/psalm/psalm --output-format=compact --no-cache

      - name: Annotate coding standards errors PHP
        if: always()
        run: cs2pr --graceful-warnings ./phpcs-report.xml
