name: PHP static code analysis

on:
  workflow_call:
    inputs:
      PHP_VERSION:
        description: PHP version with which the static code analysis is to be executed.
        default: 7.4
        required: false
        type: string
      TARGET:
        description: Array of checks to be executed.
        default: '["phpcs", "psalm"]'
        required: false
        type: string
    secrets:
      COMPOSER_AUTH_JSON:
        description: Authentication for privately hosted packages and repositories as a JSON formatted object.
        required: false

jobs:
  static-analysis:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    env:
      COMPOSER_AUTH: '${{ secrets.COMPOSER_AUTH_JSON }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.PHP_VERSION }}
          tools: composer, cs2pr

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v1
        with:
          composer-options: "--prefer-dist"

      - name: Run PHP_CodeSniffer
        if: ${{ contains(inputs.TARGET, 'phpcs') }}
        run: vendor/bin/phpcs --report-full --report-checkstyle=./phpcs-report.xml

      - name: Run Psalm
        if: ${{ contains(inputs.TARGET, 'psalm') }}
        run: vendor/bin/psalm --output-format=github --no-cache

      - name: Annotate static code analysis violations
        if: ${{ always() && contains(inputs.TARGET, 'phpcs') }}
        run: cs2pr --graceful-warnings ./phpcs-report.xml
